exports.storageAppMsg = require("./storage-app-msg.js")
exports.storageAppMsgClone = require("./storage-app-msg-clone.js")
exports.storageDSGreeting = require("./storage-ds-greeting.js")
exports.setStorageAppMsg = require("./storage-app-msg-set.js")
exports.setStorageDSGreeting = require("./storage-ds-greeting-set.js")
exports.callHello = require("./call-hello.js")
exports.callGoodbye = require("./call-goodbye.js")
