exports.deployFacet = require("./facet-deploy.js")
exports.upgradeFacet = require("./facet-upgrade.js")
exports.removeFacet = require("./facet-remove.js")
exports.addCut = require("./cut-add.js")
exports.replaceCut = require("./cut-replace.js")
exports.callHello = require("./call-hello.js")
exports.callGoodbye = require("./call-goodbye.js")
