/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDiamondCut } from "./IDiamondCut";
export type { IDiamondLoupe } from "./IDiamondLoupe";
export type { IERC1155 } from "./IERC1155";
export type { IERC1155Receiver } from "./IERC1155Receiver";
export type { IERC165 } from "./IERC165";
export type { IERC173 } from "./IERC173";
export type { IERC20 } from "./IERC20";
export type { IERC20Burnable } from "./IERC20Burnable";
export type { IERC20Events } from "./IERC20Events";
export type { IERC20Mintable } from "./IERC20Mintable";
export type { IERC721 } from "./IERC721";
export type { IERC721Receiver } from "./IERC721Receiver";
