/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockERC20Facet } from "./MockERC20Facet";
export type { MockERC721Facet } from "./MockERC721Facet";
